### ISSUE TITLE
Possible Bug (Edit card)

### ISSUE THREAD

**Issue by schlundus** [mkloubert/vscode-kanban#13]
When i click on Edit Card, always the same short description (of the last Card i edited) is displayed regardless which Card i edit.... 
The data is stored correctly

**Comment by mkloubert** [comment]
@schlundus 

**Bug should be fixed since version 1.17.4.**

This was a display bug. The underlying [syntax editors](https://codemirror.net/) have to be refreshed manually, after popup has been displayed.

**Comment by AlbertoBonfiglio** [comment]
Hi I am running version 1.23.1 and a similar issue is occurring to me. How do you manually refresh the underlying syntax editors?

VSCode
Version: 1.30.2
Commit: 61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
Date: 2019-01-07T22:49:48.319Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.18.0-13-generic
