### ISSUE TITLE
Open in new window

### ISSUE THREAD

**Issue by gianlazz** [mkloubert/vscode-kanban#19]
Is there a way to open the board in a new window? Particularly for Mac.

"cmd + k, o" opens the current file in a new window however this doesn't seem to work as it seems to need the workspace to open however vscode seems to only allow one window with a particular workspace open at a time.

**Comment by HamzaAnis** [comment]
Visual code allows to open one work space in a multiple windows . See [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

- First of all open a new window with `cmd+ shift +n`
- Then select File > Add Folder to Workspace and select the folder which has the vscode-kanban configurations.
- Open bord from the command pallete.

It will work like charm. You can close this issue. ;)

**Comment by gianlazz** [comment]
Awesome, thank you!
