### ISSUE TITLE
Move tab to another window 

### ISSUE THREAD

**Issue by samael205** [mkloubert/vscode-kanban#3]
Hello,

I do not have the possibility to move the kanban tab to another open window of VSCode.
Normally when I do this with other files, they act as if the tab is copied in the other tab and they belong both open, but this with the extension I can not do it.

**Comment by mkloubert** [comment]
@samael205 

Sorry for the late answer: I think the problem is, that this is currently not supported by the WebView API of Visual Studio Code. Only editor tabs can be moved, but no browser based ones.
