### ISSUE TITLE
🔔🔔🔔 NEED YOUR HELP FOR REFACTORING 🔔🔔🔔

### ISSUE THREAD

**Issue by mkloubert** [mkloubert/vscode-kanban#53]
Hi!

After a long time, I have decided to refactor and redesign the extension completly.

As you can see: I have not much time to do all the tasks, so I'd like to ask you for help.

My main goals are:

* replace jQuery with cleaner React and more powerful code, e.g.: https://github.com/lourenci/react-kanban
* much better design with adding features like [Add "deadline" and "finisheddate" attributes for the card.](https://github.com/mkloubert/vscode-kanban/pull/46) by @gxglhyy
* multi designs (with **dark mode**)
* **own icon**
* offline and online mode (online mode means: connect to APIs like Trello)
* more time tracker support, like [Clockify](https://clockify.me/)

And of course the other stuff here in [that issue section](https://github.com/mkloubert/vscode-kanban/issues). ;-)

That post should be the start point for you and others, so feel free to post your ideas here.

**Comment by mkloubert** [comment]
FYI: @blake-mealey @heartacker @lonix1 @klauern @tkoelpin

**Comment by floatval** [comment]
@mkloubert 
Thanks for all your work!
Can we have a functional which like maxium item window?
As you know,it's very useful when sometimes we would like choose the special item for others

**Comment by pbrilius** [comment]
Redirected from **MS VS Code**, nothing to refactor.

**Comment by pmiossec** [comment]
That's perhaps the good occasion to give some love to #23...

Thanks for the work.

**Comment by tiaghoalves** [comment]
Hi guys,

It's a pretty cool ideia, I'd like to contribute to it to improve me React skills as well. I see this refactoring as a good start for my purpose.
Well it's Hacktober fest, so I'd add a tagged to this issue indicating help wanted. In order to reach people interested to help.

**Comment by mkloubert** [comment]
@tiaghoalves 

Awesome!

I have created a new issue, that describes how: https://github.com/mkloubert/vscode-kanban/issues/54

I prepared a repository with an working example app here: https://github.com/vscode-kanban/view

Fork it and do whatever you want :-)

I created it with the following features:

* [CodeMirror](https://codemirror.net/)
* [filterex](https://github.com/m93a/filtrex)
* [highlight.js](https://highlightjs.org/)
* [i18next](https://react.i18next.com/)
* [mermaid](https://mermaid-js.github.io/mermaid/)
* [Moment.js](https://momentjs.com/)
* [React Router](https://reactrouter.com/)
* [Redux](https://redux.js.org/) + [Thunk](https://github.com/reduxjs/redux-thunk) + [DevTools](https://github.com/zalmoxisus/redux-devtools-extension)
* [SASS](https://github.com/sass/node-sass)
* [Showdown](https://github.com/showdownjs/showdown)
* [Visual Studio Code Debugging](https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react)

I did not setup a UI framework yet. It is still based on `create-react-app`. You can choose what you like best / is best.

**Comment by pbrilius** [comment]
Hopefully you'll get some.

**Comment by vip20** [comment]
@mkloubert  I tried something similar [here in marketplace](https://marketplace.visualstudio.com/items?itemName=vip20.vscode-agile-board). Would you mind giving it a try?

**Comment by mkloubert** [comment]
I have started to reorganize the refactoring of the extension, I am on a good way:


https://user-images.githubusercontent.com/4951215/200324635-827d6329-922b-4a1a-81cd-a3b44f36be89.mov



If you like to contribute, [read the Contribution thread in the new repository](https://github.com/vscode-kanban/vscode-kanban/issues/16) for more information.
