### ISSUE TITLE
🔨🔨🔨 [REFACTORING] New Board Design 🔨🔨🔨

### ISSUE THREAD

**Issue by mkloubert** [mkloubert/vscode-kanban#54]
If you like to create a new view, you can fork the following repository:

https://github.com/vscode-kanban/view

In my opinion, the best thing is, that you create a full working mock with all features. I will be the one, that connects the VS Code WebView later, after the view has been finished.

Have a look at the following files

* [board.js](https://github.com/mkloubert/vscode-kanban/blob/master/src/res/js/board.js)
* [script.js](https://github.com/mkloubert/vscode-kanban/blob/06d5982fceab3444e0dcc9af211226756b90ddf2/src/res/js/board.js#L1921)

to get an idea how data is send between VSCode and the WebView.

`vsckb_post()` is currently the function that sends data from WebView to VSCode.

`window.addEventListener('message', (e) => {})` is the callback that receives data from VSCode.

Please use the issue tracker at the new location: https://github.com/vscode-kanban/view/issues

Create your pull requests here: https://github.com/vscode-kanban/view/pulls

**Comment by mkloubert** [comment]
FYI: @tiaghoalves

**Comment by ronaldohoch** [comment]
What kind of refactoring? A better/new/modder layout?

**Comment by mkloubert** [comment]
@ronaldohoch @tiaghoalves

Correct.

The current design is based on Bootstrap 4 and does not really fit with the design of VSCode.

So, the new design should be much more modern and fit with VSCode, maybe like

![Project Dashboard screenshot](https://github.com/Kruemelkatze/vscode-dashboard/raw/master/screenshot.png)
(https://marketplace.visualstudio.com/items?itemName=kruemelkatze.vscode-dashboard)

**Comment by mkloubert** [comment]
@tiaghoalves

Did you have time to start, and if yes: Do you have a prototype to watch?

Let me know, if you have questions / problems etc.

**Comment by tiaghoalves** [comment]
@mkloubert  I'm sorry,

I didn't have much time as I expected, so couldn't take a look more deeply and start changing things. But, I'm keep tracking with the refactoring ideia and willing to try it out do some changes.

I hope to get some time to spend on this project, as soon it's possible

**Comment by abhayshiro-hfc** [comment]
I can help

**Comment by AlbertoBonfiglio** [comment]
Hi what is the status of the refactoring? I can help. I was using atlassian board bit it's being discontinued so why not make this better? Let me know if there are any areas wyou'd like me to start with if this refactoring is still ongoing. Is there a branckh we should fork from where some work was already done?

**Comment by mkloubert** [comment]
I have started to reorganize the refactoring of the extension, I am on a good way:


https://user-images.githubusercontent.com/4951215/200324635-827d6329-922b-4a1a-81cd-a3b44f36be89.mov



If you like to contribute, [read the Contribution thread in the new repository](https://github.com/vscode-kanban/vscode-kanban/issues/16) for more information.
