### ISSUE TITLE
Is it possible to add the Kanban to the activity bar?

### ISSUE THREAD

**Issue by GuidoS** [mkloubert/vscode-kanban#6]
Would it be possible to add the kanban to the activity bar. Perhaps using the side bar as a vertical kanban?

**Comment by mkloubert** [comment]
@GuidoS 

Sorry for the late answer: What do you mean with "acitivity bar"? A view between the left icons and the right editor area, like a tree explorer?

**Comment by GuidoS** [comment]
The activity bar is the one all the way to the left (a): https://code.visualstudio.com/docs/getstarted/userinterface

**Comment by mkloubert** [comment]
@GuidoS 

Unfortunatly not.

You can define custom icons in the activity bar, but only as [TreeView](https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-view-sample/USAGE.md). The extension itself only make use of new [WebView](https://code.visualstudio.com/docs/extensions/webview), which is not able to be registrated as view for the activity bar.

**Comment by GuidoS** [comment]
Thank you for the information.
