### ISSUE TITLE
What happens with the links in markdown format?

### ISSUE THREAD

**Issue by samael205** [mkloubert/vscode-kanban#7]
Hello,

First of all, I wanted to thank you for this great extension you have. It helps me a lot to organize myself.

I've seen the last update, and I'm testing the Details in Markdown with links, and when I double click to see the description in non-editable mode, the links appear as plain text
![errorkanbanlink](https://user-images.githubusercontent.com/649740/41222509-5f56a270-6d67-11e8-8319-ae61ac25838c.jpg)
![errorkanban2](https://user-images.githubusercontent.com/649740/41222512-63b5f140-6d67-11e8-9ae6-8a68f4e50209.jpg)

Or is it something I'm doing wrong?

**Comment by mkloubert** [comment]
The WebView of VSCode does not support links which are generated dynamically by JavaScript.

This is why I convert them to plain text, because otherwise, if you click on one nothing would happen.

**Comment by samael205** [comment]
ah, it's good to know.

Thank you

**Comment by samael205** [comment]
Thank, Works fine!
