### ISSUE TITLE
Key Esc when you are editing

### ISSUE THREAD

**Issue by samael205** [mkloubert/vscode-kanban#8]
HI,
When I am editing a card, and I press the Esc key, the card closes without asking if I want to save, or I really want to exit. It would be nice to ask you how you ask when you are going to eliminate a card

**Comment by samael205** [comment]
Hello,

It still happens that when I press the ESC key, the modal is closed

**Comment by mkloubert** [comment]
@samael205 

Can you test it if it works for you, **should be implemented with version 1.16.0**.

**Comment by samael205** [comment]
Ok, i will try, give me a moment

**Comment by samael205** [comment]
Now it works correctly. At least on Linux
